import {StyleSheet} from 'react-native';
const Styles = StyleSheet.create({
  login_container: {
    flex: 1,
    backgroundColor: '#FFF',
  },
  login_header: {
    alignItems: 'center',
    paddingTop: 30,
    paddingBottom: 50,
    backgroundColor: '#208AEC',
  },
  login_header_logo: {
    width: 220,
    resizeMode: 'contain',
  },
  login_header_text: {
    marginTop: 15,
    color: '#f0f0f0',
    fontSize: 16,
  },
  login_header_text_bold: {
    color: '#fff',
    fontWeight: 'bold',
  },
  login_wrapper: {
    flex: 0,
    justifyContent: 'space-between',
    paddingVertical: 10,
    borderTopRightRadius: 12,
    borderTopLeftRadius: 12,
    marginTop: 100,
    backgroundColor: '#fff',
    alignItems: 'center',
  },
  form: {
    width: '100%',
    maxWidth: 280,
  },
  TextForm: {
    fontSize: 25,
    fontWeight: "bold",
    textAlign: "center",
    color: "black",
    marginBottom:50,
  },
  form_input: {
    height: 44,
    paddingHorizontal: 10,
    marginBottom: 25,
    backgroundColor: '#EDF0F7',
    borderRadius: 10,
  },
  button: {
    alignItems: 'center',
    justifyContent: 'center',
    height: 44,
    backgroundColor: '#0065A4',
    borderRadius: 50,
  },
  button_label: {
    color: '#fff',
    fontSize: 15,
  },
  login_social: {
    width: '100%',
    maxWidth: 280,
    marginTop: 20,
  },
  login_social_separator: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  login_social_separator_line: {
    flex: 1,
    width: '100%',
    height: 1,
    backgroundColor: '#E0E0E0',
  },
  login_social_separator_text: {
    marginHorizontal: 10,
    color: '#808080',
    fontSize: 16,
  },
  login_social_buttons: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 20,
  },
  login_social_button: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 60,
    height: 60,
    marginHorizontal: 12,
    borderWidth: 1,
    borderColor: '#E7E7E7',
    borderRadius: 60,
  },
  login_social_icon: {
    width: 38,
    height: 38,
    resizeMode: 'contain',
  },
  login_social_facebook: {
    backgroundColor: '#4267B2',
    borderColor: '#4267B2',
  },
  login_footer_text: {
    flexDirection: 'row',
    alignItems: 'center',
    color: '#808080',
    fontSize: 15,
  },
  login_footer_link: {
    color: '#208AEC',
    fontSize: 15,
    fontWeight: 'bold',
  },
    container: {
    flex: 1,
    justifyContent: "center",
    backgroundColor: "white",
  },
  logoImage: {
    width: '28%',
    height: '6%',
    marginTop: '2%',
  },
  heartRateTitleText: {
    fontSize: 25,
    fontWeight: "bold",
    textAlign: "center",
    marginHorizontal: 20,
    justifyContent: "center",
    alignItems: "center",
    color: "black",
    marginTop: 325,
  },
  buttonStyle: {
    marginTop: 50,
    marginLeft:550,
    marginHorizontal: 40,
    justifyContent: 'space-evenly',
  },
  alternativeLayoutButtonContainer: {
    marginTop: 15,
    marginLeft:40,
    marginHorizontal: 40,
    alignContent:'center',
    justifyContent: 'space-evenly',
  },
  alternativeLayoutButtonContainer1: {
    marginTop: 15,
    marginLeft:40,
    marginHorizontal: 166,
    alignContent:'center',
    justifyContent: 'space-evenly',
  },
  alternativeLayoutButtonContainer2: {
    marginTop: 40,
    marginLeft:40,
    marginHorizontal: 40,
    alignContent:'center',
    justifyContent: 'space-evenly',
  },
  textStyle: {
    textAlign: 'center',
    color: 'black',
    fontWeight: "bold",
    fontSize: 26,
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 22,
  },
  aligncontainer: {
    flex: 1,
    justifyContent: "center",
    backgroundColor: "white",
    maxHeight:100,    
  },
  aligncontainerchart: {
    flex: 1,
    justifyContent: "center",
    backgroundColor: "white",
    maxHeight:200,
    marginTop: 10   
  },
  alignbutton: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 4,
    elevation: 3,
    backgroundColor: 'black',
  },
  fixToText: {
    flex: 0,
    flexDirection: 'row',
    justifyContent: 'space-between'
  },
  TitleText: {
    fontSize: 25,
    fontWeight: "bold",
    textAlign: "center",
    marginHorizontal: 20,
    marginTop: 250,
    color: "black",
  },
  TitleButton: {
    fontSize: 25,
    fontWeight: "bold",
    textAlign: "center",
    marginHorizontal: 20,
    marginTop: 100,
    color: "black",
  },
  graphcontainer: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "white"
  },
  chartcontainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "lightblue",
    marginTop: 40,
    maxHeight: 415,
  },
  Textcontainer: {
    flex: 1,
    backgroundColor: "white",
    marginTop: 0,
    maxHeight: 115,
    justifyContent: "center",
    alignItems: "center",
  },
  heartRateTitleWrapper: {
    flex: 1,
    alignItems: "center",
  },
  FrequencyTitleText: {
    fontSize: 30,
    fontWeight: "bold",
    textAlign: "center",
    marginHorizontal: 20,
    color: "grey",
    marginTop:30
  },
  batteryTitleText: {
    fontSize: 20,
    fontWeight: "bold",
    color: "black",
    marginLeft: 520,
  },
  connectionText: {
    fontSize: 20,
    fontWeight: "bold",
    color: "green",
    marginLeft: 530,
  },
  hourText: {
    fontSize: 19,
    fontWeight: "bold",
    color: "black",
    marginRight: 600,
  },

  FrequencyTitleText1: {
    fontSize: 70,
    fontWeight: "bold",
    textAlign: "center",
    marginHorizontal: 20,
    color: "black",
  },
  heartRateText: {
    fontSize: 25,
    marginTop: 15,
  },
  ctaButton: {
    backgroundColor: "lightblue",
    justifyContent: "center",
    alignItems: "center",
    height: 50,
    marginHorizontal: 20,
    marginBottom: 5,
    borderRadius: 8,
  },
  ctaButtonText: {
    fontSize: 25,
    justifyContent: "center",
    alignItems: "center",
    fontWeight: "bold",
    color: "white",
  },
  appColors: {
    color: '#007FFF',
    primaryInactive: 'rgba(0,127,255,0.75)',
    secondary: '#99FFFF',
    error: '#fc6d47',
},
});

export default Styles;
